apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: crypto-trend
spec:
  selector:
    app: namenode
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: web
      port: 9870
      targetPort: 9870
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: crypto-trend
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: hdfs-config
          env:
            - name: CLUSTER_NAME
              value: crypto-hdfs
          ports:
            - containerPort: 9000
              name: rpc
            - containerPort: 9870
              name: web
          volumeMounts:
            - name: namenode-data
              mountPath: /hadoop/dfs/name
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 45
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: namenode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
