"""MongoDB helper for crypto trend analytics datasets."""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from pymongo import ASCENDING, DESCENDING, MongoClient
from pymongo.collection import Collection
from pymongo.errors import PyMongoError


class MongoStorageError(RuntimeError):
    """Raised when a MongoDB operation fails."""


@dataclass
class MongoConfig:
    """Configuration for MongoDB access."""

    uri: str = os.getenv("MONGO_URI", "mongodb+srv://tranduonganttcole_db_user:KrHMQZxRZlRAsA3B@cluster0.rrajasg.mongodb.net/?appName=Cluster0")
    database: str = os.getenv("MONGO_DB", "crypto_trends")


class MongoStorageClient:
    """Persistence gateway for processed indicators and alerts."""

    def __init__(self, config: Optional[MongoConfig] = None) -> None:
        self.config = config or MongoConfig()
        self._client = MongoClient(self.config.uri)
        self.db = self._client[self.config.database]

    def healthcheck(self) -> bool:
        """Return True when ping command succeeds."""
        try:
            self._client.admin.command("ping")
            return True
        except PyMongoError:
            return False

    def ensure_indexes(self) -> None:
        """Create indexes used by realtime dashboard and alert queries."""
        try:
            self.db.tweets.create_index([("coin", ASCENDING), ("created_at", DESCENDING)])
            self.db.sentiment_metrics.create_index([("coin", ASCENDING), ("window_start", DESCENDING)])
            self.db.trend_spikes.create_index([("keyword", ASCENDING), ("detected_at", DESCENDING)])
            self.db.market_prices.create_index([("symbol", ASCENDING), ("timestamp", DESCENDING)])
            self.db.alerts.create_index([("status", ASCENDING), ("created_at", DESCENDING)])
        except PyMongoError as exc:
            raise MongoStorageError(f"Cannot create MongoDB indexes: {exc}") from exc

    def _insert_one(self, collection: Collection, document: dict) -> str:
        try:
            result = collection.insert_one(document)
            return str(result.inserted_id)
        except PyMongoError as exc:
            raise MongoStorageError(f"Insert failed for '{collection.name}': {exc}") from exc

    def _insert_many(self, collection: Collection, documents: list[dict]) -> int:
        if not documents:
            return 0
        try:
            result = collection.insert_many(documents)
            return len(result.inserted_ids)
        except PyMongoError as exc:
            raise MongoStorageError(f"Bulk insert failed for '{collection.name}': {exc}") from exc

    def save_raw_tweets(self, tweets: list[dict]) -> int:
        """Store raw tweets for long-tail querying and audits."""
        return self._insert_many(self.db.tweets, tweets)

    def save_sentiment_metric(
        self,
        coin: str,
        bullish_ratio: float,
        bearish_ratio: float,
        neutral_ratio: float,
        fear_greed_score: float,
        window_start: datetime,
        window_end: datetime,
    ) -> str:
        """Store one sentiment metric snapshot for a coin/time window."""
        doc = {
            "coin": coin.upper().replace("$", ""),
            "bullish_ratio": bullish_ratio,
            "bearish_ratio": bearish_ratio,
            "neutral_ratio": neutral_ratio,
            "fear_greed_score": fear_greed_score,
            "window_start": window_start,
            "window_end": window_end,
            "created_at": datetime.utcnow(),
        }
        return self._insert_one(self.db.sentiment_metrics, doc)

    def save_trend_spike(
        self,
        keyword: str,
        mention_count: int,
        baseline_count: float,
        z_score: float,
        related_coins: list[str],
        detected_at: Optional[datetime] = None,
    ) -> str:
        """Store detected trend spike (altcoin keyword or category)."""
        doc = {
            "keyword": keyword,
            "mention_count": mention_count,
            "baseline_count": baseline_count,
            "z_score": z_score,
            "related_coins": [c.upper().replace("$", "") for c in related_coins],
            "detected_at": detected_at or datetime.utcnow(),
            "created_at": datetime.utcnow(),
        }
        return self._insert_one(self.db.trend_spikes, doc)

    def save_alert(
        self,
        alert_type: str,
        severity: str,
        message: str,
        payload: Optional[dict] = None,
    ) -> str:
        """Store alert generated by outlier or correlation rules."""
        doc = {
            "alert_type": alert_type,
            "severity": severity,
            "message": message,
            "payload": payload or {},
            "status": "open",
            "created_at": datetime.now(datetime.timezone.utc),
        }
        return self._insert_one(self.db.alerts, doc)

    def close(self) -> None:
        self._client.close()


if __name__ == "__main__":
    # Quick test of MongoDB connection and indexes
    client = MongoStorageClient()
    if client.healthcheck():
        print("MongoDB connection successful.")
        client.ensure_indexes()
        print("Indexes ensured.")
    else:
        print("MongoDB connection failed.")
    client.close()
