apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crypto-trend
resources:
  - namespace.yaml
  - storage-secrets.yaml
  - mongodb.yaml
  - hdfs/hdfs-config.yaml
  - hdfs/namenode.yaml
  - hdfs/datanode.yaml
